baseURL = "/"
defaultContentLanguage = "es"
title = "El Médico Social"

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[params]
  colorScheme = "blowfish"
  enableSearch = true
  logo = "img/logo.png"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false    <-- esta línea
  showScrollToTop = true

  
