# Apariencia general
colorScheme = "forest"
defaultAppearance = "light"
autoSwitchAppearance = true
 mainSections = ["posts"]

# Información del autor (la barra lateral)
[author]
  name = "Dr.del Sur"
  headline = "Médico"
  bio = "Escribo sobre medicina social y salud pública."
 
  

# Menú de navegación (los enlaces de arriba)


# Configuración del artículo (los posts)
[article]
  showDate = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true

# Pie de página
[footer]
  showCopyright = true
  showThemeAttribution = true

# Homepage (la página de inicio)
[homepage]
  layout = "profile"
  showRecent = true
  recentPostsLimit = 5

# Cabecera
[header]
  layout = "left"
