# Apariencia general
colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true
mainSections = ["posts"]

# Información del autor (la barra lateral)
[author]
  name = "Dr. del Sur"
  #headline = "Médico"
  bio = "Escribo sobre medicina social y salud pública."
 
  

# Menú de navegación (los enlaces de arriba)


# Configuración del artículo (los posts)
[article]
  showViews = true
  showLikes = true
  showDate = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showComments = true

# Pie de página
[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  autoSwitchAppearance = false

# Homepage (la página de inicio)
[homepage]
  layout = "profile"
  showRecent = true
  recentPostsLimit = 5
  mainSections = ["posts"]
  cardView = true
  showSummary = true   # <-- Añade esto
  showTitle = true 

# Cabecera
[header]
  layout = "left"

# Vista de lista (página de Artículos)
[list]
  cardView = true
  showSummary = true   # <-- Añade esto

[firebase]
  apiKey = "AIzaSyBm07z7hAU6TlZVubrAlbfOjr3C3NUYmrA"
  authDomain = "medicosocial1-b7e67.firebaseapp.com"
  projectId = "medicosocial1-b7e67"
  storageBucket = "medicosocial1-b7e67.firebasestorage.app"
  messagingSenderId = "980788347502"
  appId = "1:980788347502:web:773c228e9d66eb055cdc7f"
  measurementId = "G-7TC934H0R2"
  
